pipeline:
  build:
    image: python:latest
    commands:
      - pip install -r requirements.txt -r requirements_dev.txt
      - python -m pytest tests/ -v

  pypi:
    image: plugins/s3
    bucket: pypi.pumperkin.com
    access_key: access_key
    secret_key: secret_key
    region: eu-west-1
    source: /
    target: /
    when:
      branch: master
