pipeline:
  build:
    image: python:latest
    commands:
      - pip install -r requirements.txt -r requirements_dev.txt
      - python -m pytest tests/ -v

  pypi_publish:
    image: gjtempleton/drone-pypi
    repository: http://pypi.pumperkin.com/pypi
    distributions:
      - sdist
      - bdist_wheel
    when:
      branch: master
