---
pipeline:
  build:
    image: python:latest
    commands:
      - pip install -r requirements.txt -r requirements_dev.txt
      - python -m pytest tests/ -v
      - python3 setup.py sdist bdist_wheel

  publish:
    pypi:
      image: misdirectedpuffin/s3-pypi-publisher
      bucket: pypi.pumperkin.com
      region: eu-west-1
      wheel: true
      sdist: true
      when:
        branch: master
